language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -U -r test_requirements.txt --use-mirrors
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf c2c372b16ab98e00fddcb56d818ee5be435d37ec
  - py.test example/tests.py --cov=example
  - cd -
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing --cov-report xml --cov openpyxl --junit-xml=shippable/testresults/results.xml
after_success:
  - coveralls
